name: autotuning
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - pytorch=2.3.0
  - pytorch-cuda=12.4
  - torchaudio
  - torchvision
  - ffmpeg
  - libsndfile
  - numpy
  - matplotlib
  - scipy
  - pandas
  - ipython
  - jupyterlab
  - librosa
  - ca-certificates
  - openssl
  - av
  - ffmpeg
  
  - pip:
      - git+https://github.com/gruporaia/TTS-Utils.git
      - git+https://github.com/idiap/coqui-ai-TTS.git
      - streamlit
      - datasets==3.6.0
      - snac==1.2.1
      - unsloth==2025.5.7
      - pip install torch==2.6.0 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124_full --force-reinstall
